package dev.betterlitematica.selftest;

import dev.betterlitematica.core.*;
import dev.betterlitematica.io.*;
import java.io.*;
import java.nio.file.*;
import java.util.*;
import java.util.concurrent.atomic.AtomicInteger;

/** Complete-source geometry and persisted image contracts, independent of Minecraft. */
public final class SchematicPreviewChecks {
    private static int checks;
    @FunctionalInterface private interface Task{void run()throws Exception;}
    private static void check(boolean value,String message){checks++;if(!value)throw new AssertionError(message);}
    private static void cancelled(Task action)throws Exception{try{action.run();throw new AssertionError("Cancellation ignored");}catch(InterruptedIOException expected){checks++;}}
    private static void invalidOrbit(byte[] bytes)throws Exception{try{SchematicPreview.readOrbitModel(new DataInputStream(new ByteArrayInputStream(bytes)),Cancellation.NEVER);throw new AssertionError("Malformed orbit accepted");}catch(IOException expected){checks++;}}
    private static void png(Path path,int[] pixels)throws IOException{var image=new java.awt.image.BufferedImage(256,256,java.awt.image.BufferedImage.TYPE_INT_ARGB);image.setRGB(0,0,256,256,pixels,0,256);javax.imageio.ImageIO.write(image,"png",path.toFile());}
    private static Map<String,Object> root(Map<String,Object> regions){return Fixtures.litematic(regions,"preview fixture");}
    private static Map<String,Object> region(int x,int y,int z,int sx,int sy,int sz,int[] values){var tag=Fixtures.region(x,y,z,sx,sy,sz,i->0);tag.put("BlockStatePalette",List.of(Fixtures.state("minecraft:air"),Fixtures.state("minecraft:red_concrete"),Fixtures.state("minecraft:green_concrete"),Fixtures.state("minecraft:blue_concrete")));tag.put("BlockStates",PackedBits.pack(2,values).copyWords());return tag;}
    private static SchematicPreview.Images render(Map<String,Object> root)throws IOException{var g=SchematicPreview.readGeometry(root,Cancellation.NEVER);int[] colors=g.palette().stream().mapToInt(s->s.name().contains("red")?0xffff2020:s.name().contains("green")?0xff20ff20:0xff2020ff).toArray();return SchematicPreview.render(g,colors,Cancellation.NEVER);}
    private static int count(int[] view){int n=0;for(int pixel:view)if((pixel>>>24)!=0)n++;return n;}
    private static double[] center(int[] pixels,int channel){double x=0,y=0,n=0;for(int i=0;i<pixels.length;i++){int p=pixels[i];if((p>>>24)==0)continue;int r=(p>>>16)&255,g=(p>>>8)&255,b=p&255;if(channel==0?r>g*2&&r>b*2:channel==1?g>r*2&&g>b*2:b>r*2&&b>g*2){x+=i%256;y+=i/256;n++;}}return new double[]{x/Math.max(1,n),y/Math.max(1,n),n};}
    private static void same(SchematicPreview.Images a,SchematicPreview.Images b,String text){check(a!=null&&b!=null&&a.size().equals(b.size())&&a.blocks()==b.blocks(),text+" metadata");for(int i=0;i<4;i++)check(Arrays.equals(a.views().get(i),b.views().get(i)),text+" view "+i);}
    private static int[] renderOrbitFixture(Map<String,Object> source,double yaw,double pitch)throws IOException{var g=SchematicPreview.readGeometry(source,Cancellation.NEVER);int[] colors=g.palette().stream().mapToInt(v->v.name().contains("red")?0xffff2020:v.name().contains("green")?0xff20ff20:0xff2020ff).toArray();return SchematicPreview.renderOrbit(SchematicPreview.createOrbitModel(g,colors,Cancellation.NEVER),yaw,pitch,false,Cancellation.NEVER);}
    public static int run(Path temp)throws Exception{
        checks=0;Files.createDirectories(temp);int[] cells=new int[5*3*5];cells[0]=1;cells[4]=2;cells[0+4*5+2*25]=3;
        var source=root(Map.of("main",region(0,0,0,5,3,5,cells)));var geometry=SchematicPreview.readGeometry(source,Cancellation.NEVER);var images=render(source);
        check(geometry.size().equals(new Vec3i(5,3,5))&&geometry.blocks()==3&&geometry.palette().size()==3,"Complete bounds, palette and visible source count");
        for(var view:images.views()){check(count(view)>0&&count(view)<256*256,"Every view nonempty with transparent margin");check(view[0]==0,"Transparent corner");}
        var front=images.views().get(0);check(center(front,0)[0]<center(front,1)[0],"Front from +Z shows +X to right");check(center(front,2)[1]<center(front,0)[1],"Front shows +Y upwards");
        var side=images.views().get(1);check(center(side,2)[0]<center(side,1)[0],"Side from +X shows +Z to left");check(center(side,0)[2]==0&&center(side,1)[2]>0,"Side depth picks near +X green over red");
        var top=images.views().get(2);check(center(top,2)[1]>center(top,0)[1],"Top puts +Z toward bottom");check(center(top,0)[0]<center(top,1)[0],"Top keeps +X to right");
        check(!Arrays.equals(front,side)&&!Arrays.equals(front,top)&&!Arrays.equals(top,images.views().get(3)),"Asymmetric source produces four distinct views");
        for(int c=0;c<3;c++)check(center(images.views().get(3),c)[2]>0,"Isometric includes each visible colored voxel");
        var translated=root(Map.of("main",region(-50,-39,-82,5,3,5,cells)));same(images,render(translated),"Negative translation invariant rendering");
        var signed=root(Map.of("main",region(4,2,4,-5,-3,-5,cells)));same(images,render(signed),"Signed size normalizes source anchor");
        for(int format:new int[]{2,3}){var sponge=Fixtures.sponge(format,4,2,3,i->i%4,new int[]{0,1,2,3});if(format==3){var nested=NbtReader.compound(sponge.get("Schematic"),"Schematic");nested.put("DataVersion",3465);sponge.put("Schematic",nested);}else sponge.put("DataVersion",3465);var converted=render(sponge);check(converted.blocks()==18&&converted.views().stream().allMatch(v->count(v)>0),"Sponge v"+format+" without auxiliary NBT renders");SchematicPreview.embed(sponge,converted,Cancellation.NEVER);same(converted,SchematicPreview.embedded(sponge,Cancellation.NEVER),"Sponge embedded digest v"+format);}
        var overlap=root(new LinkedHashMap<>(Map.of("a",region(0,0,0,1,1,1,new int[]{1}),"b",region(0,0,0,1,1,1,new int[]{0}))));check(render(overlap).blocks()==1&&center(render(overlap).views().get(0),0)[2]>0,"Later region air never erases earlier source block");
        overlap=root(Map.of("a",region(0,0,0,1,1,1,new int[]{1}),"b",region(0,0,0,1,1,1,new int[]{2})));check(center(render(overlap).views().get(0),1)[2]>0&&center(render(overlap).views().get(0),0)[2]==0,"Sorted later non-air region wins exact overlap");
        int[] sparse=new int[1024];sparse[0]=1;sparse[1023]=2;var wide=render(root(Map.of("wide",region(-512,-39,0,1024,1,1,sparse))));check(wide.blocks()==2&&center(wide.views().get(0),0)[2]>0&&center(wide.views().get(0),1)[2]>0,"LOD includes both remote ends, not a residency window");
        var invisible=region(0,0,0,3,1,1,new int[]{1,2,3});invisible.put("BlockStatePalette",List.of(Fixtures.state("minecraft:air"),Fixtures.state("minecraft:light"),Fixtures.state("minecraft:barrier"),Fixtures.state("minecraft:structure_void")));var blank=render(root(Map.of("invisible",invisible)));check(blank.blocks()==0&&blank.views().stream().allMatch(v->count(v)==0),"Invisible helper blocks do not obscure the model");
        var broken=region(0,0,0,1,1,1,new int[]{3});broken.put("BlockStatePalette",List.of(Fixtures.state("minecraft:air")));try{SchematicPreview.readGeometry(root(Map.of("bad",broken)),Cancellation.NEVER);throw new AssertionError("Bad palette index accepted");}catch(IOException expected){checks++;}
        cancelled(()->SchematicPreview.readGeometry(source,()->true));cancelled(()->SchematicPreview.render(geometry,new int[]{1,2,3},()->true));
        var calls=new AtomicInteger();cancelled(()->SchematicPreview.render(geometry,new int[]{-1,-1,-1},()->calls.incrementAndGet()>5));
        int[] returned=images.views().get(0);returned[0]=-1;check(images.views().get(0)[0]==0,"Images do not expose mutable internal pixels");
        check(SchematicPreview.embedded(source,Cancellation.NEVER)==null,"No embedded image is a cache miss");SchematicPreview.embed(source,images,Cancellation.NEVER);same(images,SchematicPreview.embedded(source,Cancellation.NEVER),"In-memory geometry checked embed");
        Path original=temp.resolve("one.litematic"),copy=temp.resolve("renamed.litematic");NbtWriter.writeNew(original,source,Cancellation.NEVER);Files.copy(original,copy);same(images,SchematicPreview.embedded(NbtReader.read(copy,NbtReader.Limits.DEFAULT,Cancellation.NEVER),Cancellation.NEVER),"Embedded images survive new path");
        var metadata=NbtReader.compound(source.get("Metadata"),"Metadata");check(Arrays.equals((int[])metadata.get("PreviewImageData"),images.views().get(3)),"Standard preview is isometric ARGB");metadata.put("Name","renamed display name");source.put("Metadata",metadata);check(SchematicPreview.embedded(source,Cancellation.NEVER)!=null,"Metadata-only rename does not invalidate geometry");
        var reg=NbtReader.compound(NbtReader.compound(source.get("Regions"),"Regions").get("main"),"main");long[] packed=(long[])reg.get("BlockStates");long saved=packed[0];packed[0]^=1;check(SchematicPreview.embedded(source,Cancellation.NEVER)==null,"Packed geometry edit invalidates stale images");packed[0]=saved;
        var sourceRegions=source.get("Regions");var moved=new LinkedHashMap<>(reg);moved.put("Position",Fixtures.xyz(-1,0,0));source.put("Regions",Map.of("main",moved));check(SchematicPreview.embedded(source,Cancellation.NEVER)==null,"Position edit invalidates embedded geometry");source.put("Regions",sourceRegions);
        var recolored=new LinkedHashMap<>(reg);var editedPalette=new ArrayList<Object>((List<?>)reg.get("BlockStatePalette"));editedPalette.set(1,Fixtures.state("minecraft:yellow_concrete"));recolored.put("BlockStatePalette",editedPalette);source.put("Regions",Map.of("main",recolored));check(SchematicPreview.embedded(source,Cancellation.NEVER)==null,"Palette change invalidates embedded geometry");source.put("Regions",sourceRegions);
        var savedEnvelope=NbtReader.compound(metadata.get("BetterLitematicaPreview"),"preview");@SuppressWarnings("unchecked") List<int[]> savedViews=(List<int[]>)savedEnvelope.get("Views");savedViews.get(0)[100]^=123;check(SchematicPreview.embedded(source,Cancellation.NEVER)==null,"Embedded image CRC detects damage");SchematicPreview.embed(source,images,Cancellation.NEVER);
        cancelled(()->SchematicPreview.embedded(source,()->true));var before=source.get("Metadata");cancelled(()->SchematicPreview.embed(source,images,()->true));check(source.get("Metadata")==before,"Cancelled embedding leaves metadata untouched");
        String sha="a".repeat(64),other="b".repeat(64);var cache=new PreviewCache(temp.resolve("cache"));check(cache.read(sha,Cancellation.NEVER)==null,"Cold cache miss");cache.write(sha,images,Cancellation.NEVER);same(images,cache.read(sha,Cancellation.NEVER),"Warm CRC checked cache");check(cache.read(other,Cancellation.NEVER)==null,"Different source SHA cannot return old images");
        Path entry;try(var files=Files.list(temp.resolve("cache"))){entry=files.filter(p->p.toString().endsWith(".blpv")).findFirst().orElseThrow();}byte[] bytes=Files.readAllBytes(entry);bytes[bytes.length-20]^=44;Files.write(entry,bytes);check(cache.read(sha,Cancellation.NEVER)==null,"Corrupt disk image is a rebuildable miss");cache.write(sha,images,Cancellation.NEVER);same(images,cache.read(sha,Cancellation.NEVER),"Corrupt cache replaced atomically");
        calls.set(0);cancelled(()->cache.write(sha,blank,()->calls.incrementAndGet()>8));same(images,cache.read(sha,Cancellation.NEVER),"Cancelled replacement preserves previous entry");try(var files=Files.list(temp.resolve("cache"))){check(files.noneMatch(p->p.toString().endsWith(".part")),"Cancellation leaves no scratch file");}
        var small=new PreviewCache(temp.resolve("small-cache"),1_100_000);small.write(sha,images,Cancellation.NEVER);small.write(other,blank,Cancellation.NEVER);check(small.read(sha,Cancellation.NEVER)==null&&small.read(other,Cancellation.NEVER)!=null,"Byte budget evicts an old complete image");try(var files=Files.list(temp.resolve("small-cache"))){check(files.mapToLong(p->{try{return Files.size(p);}catch(IOException e){throw new UncheckedIOException(e);}}).sum()<=1_100_000,"Published cache stays inside disk budget");}
        Path many=temp.resolve("many-cache");Files.createDirectories(many);for(int i=0;i<600;i++)Files.write(many.resolve("v"+SchematicPreview.VERSION+"-"+String.format(Locale.ROOT,"%064x",i)+".blpv"),new byte[0]);Files.writeString(many.resolve("unrelated.txt"),"keep");new PreviewCache(many).write(sha,images,Cancellation.NEVER);try(var files=Files.list(many)){check(files.filter(p->p.toString().endsWith(".blpv")).count()<=PreviewCache.MAX_FILES,"Tiny/corrupt files also obey count budget");}check(Files.readString(many.resolve("unrelated.txt")).equals("keep"),"Eviction never removes unrelated files");
        cancelled(()->cache.read(sha,()->true));try{cache.read("../escape",Cancellation.NEVER);throw new AssertionError("Invalid hash accepted");}catch(IllegalArgumentException expected){checks++;}
        int[] colors=geometry.palette().stream().mapToInt(s->s.name().contains("red")?0xffff2020:s.name().contains("green")?0xff20ff20:0xff2020ff).toArray();var orbit=SchematicPreview.createOrbitModel(geometry,colors,Cancellation.NEVER);
        int[] defaultOrbit=SchematicPreview.renderOrbit(orbit,Math.PI/4,Math.atan(1/Math.sqrt(2)),false,Cancellation.NEVER);check(Arrays.equals(images.views().get(3),defaultOrbit),"Static isometric exactly matches orbit default framing and lighting");png(temp.resolve("asymmetric-orbit.png"),defaultOrbit);
        int[] otherAngle=SchematicPreview.renderOrbit(orbit,-Math.PI/3,-.4,false,Cancellation.NEVER);check(count(otherAngle)>0&&!Arrays.equals(defaultOrbit,otherAngle),"Negative yaw and pitch reveal different surfaces");png(temp.resolve("asymmetric-under.png"),otherAngle);
        check(Arrays.equals(SchematicPreview.renderOrbit(orbit,0,0,false,Cancellation.NEVER),SchematicPreview.renderOrbit(orbit,Math.PI*2,0,false,Cancellation.NEVER)),"Full yaw turn is periodic");
        check(Arrays.equals(defaultOrbit,SchematicPreview.renderOrbit(orbit,Math.PI/4,Math.atan(1/Math.sqrt(2)),true,Cancellation.NEVER)),"Small model keeps identical frame during drag");
        var bytesOut=new ByteArrayOutputStream();SchematicPreview.writeOrbitModel(orbit,new DataOutputStream(bytesOut),Cancellation.NEVER);byte[] orbitBytes=bytesOut.toByteArray();var restored=SchematicPreview.readOrbitModel(new DataInputStream(new ByteArrayInputStream(orbitBytes)),Cancellation.NEVER);
        check(Arrays.equals(otherAngle,SchematicPreview.renderOrbit(restored,-Math.PI/3,-.4,false,Cancellation.NEVER)),"Serialized orbit preserves full six-face data");check(Arrays.equals(defaultOrbit,SchematicPreview.renderOrbit(restored,Math.PI/4,Math.atan(1/Math.sqrt(2)),true,Cancellation.NEVER)),"Deserialization reconstructs drag geometry");
        byte[] bad=orbitBytes.clone();java.nio.ByteBuffer.wrap(bad).putInt(4,161);invalidOrbit(bad);bad=orbitBytes.clone();java.nio.ByteBuffer.wrap(bad).putInt(16,-1);invalidOrbit(bad);bad=orbitBytes.clone();java.nio.ByteBuffer.wrap(bad).putLong(28,-1);invalidOrbit(bad);bad=orbitBytes.clone();bad[38]='q';invalidOrbit(bad);bad=orbitBytes.clone();java.nio.ByteBuffer.wrap(bad).putInt(bad.length-4,999999);invalidOrbit(bad);invalidOrbit(Arrays.copyOf(orbitBytes,orbitBytes.length-3));
        cancelled(()->SchematicPreview.createOrbitModel(geometry,colors,()->true));cancelled(()->SchematicPreview.renderOrbit(orbit,0,0,true,()->true));cancelled(()->SchematicPreview.writeOrbitModel(orbit,new DataOutputStream(new ByteArrayOutputStream()),()->true));cancelled(()->SchematicPreview.readOrbitModel(new DataInputStream(new ByteArrayInputStream(orbitBytes)),()->true));
        try{SchematicPreview.renderOrbit(orbit,Double.NaN,0,true,Cancellation.NEVER);throw new AssertionError("NaN angle accepted");}catch(IllegalArgumentException expected){checks++;}
        colors[0]=0;check(Arrays.equals(defaultOrbit,SchematicPreview.renderOrbit(orbit,Math.PI/4,Math.atan(1/Math.sqrt(2)),false,Cancellation.NEVER)),"Orbit owns its color snapshot");
        int[] faces=new int[27];for(int y=0;y<3;y++)for(int z=0;z<3;z++)for(int x=0;x<3;x++)faces[x+3*(z+3*y)]=z==0?5:z==2?6:y==0?3:y==2?4:x==0?1:2;
        var cube=region(0,0,0,3,3,3,new int[27]);var cubePalette=new ArrayList<Object>();cubePalette.add(Fixtures.state("minecraft:air"));for(String color:List.of("red","green","blue","yellow","cyan","magenta"))cubePalette.add(Fixtures.state("minecraft:"+color+"_concrete"));cube.put("BlockStatePalette",cubePalette);cube.put("BlockStates",PackedBits.pack(3,faces).copyWords());var cubeModel=SchematicPreview.createOrbitModel(SchematicPreview.readGeometry(root(Map.of("cube",cube)),Cancellation.NEVER),new int[]{0xffff0000,0xff00ff00,0xff0000ff,0xffffff00,0xff00ffff,0xffff00ff},Cancellation.NEVER);
        double[][] angles={{-Math.PI/2,0},{Math.PI/2,0},{0,-Math.PI/2},{0,Math.PI/2},{Math.PI,0},{0,0}};int[] masks={4,2,1,6,3,5};
        for(int i=0;i<6;i++){var pixels=SchematicPreview.renderOrbit(cubeModel,angles[i][0],angles[i][1],false,Cancellation.NEVER);int p=pixels[128+128*256],mask=((p>>>16&255)>0?4:0)|((p>>>8&255)>0?2:0)|((p&255)>0?1:0);check(mask==masks[i],"Correct visible face from all six directions "+i);check(count(pixels)>0&&pixels[0]==0,"Rotation retains transparent margin");}
        int[] stairs=new int[12*6*6];for(int y=0;y<6;y++)for(int z=0;z<6;z++)for(int x=0;x<12;x++)if(z<1+(x/4)*2)stairs[x+12*(z+6*y)]=1;
        var stepGeometry=SchematicPreview.readGeometry(root(Map.of("steps",region(0,0,0,12,6,6,stairs))),Cancellation.NEVER);var stepImages=SchematicPreview.render(stepGeometry,new int[]{0xffdddddd,0xffdddddd,0xffdddddd},Cancellation.NEVER);
        int[] depthImage=stepImages.views().get(0);int far=depthImage[53+128*256]&255,near=depthImage[203+128*256]&255,contact=depthImage[88+128*256]&255;
        check(near>far+35,"Monochrome orthographic front shows real depth separation");check(contact<far,"Deeper plane gets local contact occlusion near the step");for(int i=0;i<4;i++)png(temp.resolve("depth-stair-"+i+".png"),stepImages.views().get(i));
        int[] padded=new int[1000];padded[500]=1;var paddedGeometry=SchematicPreview.readGeometry(root(Map.of("padded",region(0,0,0,1000,1,1,padded))),Cancellation.NEVER);var paddedModel=SchematicPreview.createOrbitModel(paddedGeometry,new int[]{-1,-1,-1},Cancellation.NEVER);check(Arrays.equals(SchematicPreview.renderOrbit(paddedModel,.7,.4,false,Cancellation.NEVER),SchematicPreview.renderOrbit(paddedModel,.7,.4,true,Cancellation.NEVER)),"Sparse padding does not inflate or clip the interactive model");
        // Independent hand-computed scene: signed source anchor (2,0,0), child +90,
        // then root mirror X. Production contract is childLinear(rootLinear(local-anchor)).
        var placedSource=root(Map.of("signed",region(2,0,0,-3,1,1,new int[]{1,0,2}),"other",region(0,0,8,1,1,1,new int[]{3})));
        var child=new RegionPlacement(new Vec3i(10,0,5),1,false,false,true,false);var overrides=Map.of("signed",child);
        var configured=SchematicPreview.readGeometry(placedSource,overrides,Cancellation.NEVER);int[] configuredColors=configured.palette().stream().mapToInt(v->v.name().contains("red")?0xffff2020:v.name().contains("green")?0xff20ff20:0xff2020ff).toArray();var configuredModel=SchematicPreview.createOrbitModel(configured,configuredColors,Cancellation.NEVER);
        var expectedIdentity=root(Map.of("a",region(10,0,3,1,1,1,new int[]{1}),"b",region(10,0,5,1,1,1,new int[]{2}),"c",region(0,0,8,1,1,1,new int[]{3})));
        check(Arrays.equals(SchematicPreview.renderOrbit(configuredModel,.7,.4,false,Cancellation.NEVER),renderOrbitFixture(expectedIdentity,.7,.4)),"Signed child anchor and relocated +90 child match independent expected world positions");
        var mirror=new PlacementTransform(new Vec3i(800,-39,-700),0,true,false);var mirrored=SchematicPreview.posedOrbitModel(configuredModel,mirror,Cancellation.NEVER);
        var expectedMirror=root(Map.of("a",region(-10,0,7,1,1,1,new int[]{1}),"b",region(-10,0,5,1,1,1,new int[]{2}),"c",region(0,0,8,1,1,1,new int[]{3})));
        check(Arrays.equals(SchematicPreview.renderOrbit(mirrored,.7,.4,false,Cancellation.NEVER),renderOrbitFixture(expectedMirror,.7,.4)),"Root mirror before child rotation; world translation ignored");
        var expectedTurn=root(Map.of("a",region(-3,0,10,1,1,1,new int[]{1}),"b",region(-5,0,10,1,1,1,new int[]{2}),"c",region(-8,0,0,1,1,1,new int[]{3})));
        var turned=SchematicPreview.posedOrbitModel(configuredModel,new PlacementTransform(Vec3i.ZERO,1,false,false),Cancellation.NEVER);check(Arrays.equals(SchematicPreview.renderOrbit(turned,-.6,-.3,false,Cancellation.NEVER),renderOrbitFixture(expectedTurn,-.6,-.3)),"Root quarter-turn matches independently calculated positions from underneath");
        var disabled=SchematicPreview.readGeometry(placedSource,Map.of("signed",child.enabled(false)),Cancellation.NEVER);check(disabled.blocks()==1,"Disabled child contributes no preview blocks");
        var disabledAll=SchematicPreview.readGeometry(placedSource,Map.of("signed",child.enabled(false),"other",new RegionPlacement(new Vec3i(0,0,8),0,false,false,false,false)),Cancellation.NEVER);check(SchematicPreview.render(disabledAll,new int[]{-1,-1,-1},Cancellation.NEVER).views().stream().allMatch(v->count(v)==0),"All disabled is valid transparent preview");
        var tinyEnabled=root(Map.of("huge",region(0,0,0,1024,1,1,new int[1024]),"small",region(0,0,2,3,1,1,new int[]{1,2,3})));var tinyGeometry=SchematicPreview.readGeometry(tinyEnabled,Map.of("huge",new RegionPlacement(Vec3i.ZERO,0,false,false,false,false)),Cancellation.NEVER);var tinyModel=SchematicPreview.createOrbitModel(tinyGeometry,new int[]{0xffff2020,0xff20ff20,0xff2020ff},Cancellation.NEVER);check(Arrays.equals(SchematicPreview.renderOrbit(tinyModel,.7,.4,false,Cancellation.NEVER),renderOrbitFixture(root(Map.of("small",region(0,0,2,3,1,1,new int[]{1,2,3}))),.7,.4)),"Disabled huge region cannot reduce the detail of an enabled small region");
        var locked=new RegionPlacement(child.position(),child.quarterTurns(),child.mirrorX(),child.mirrorZ(),child.enabled(),true);check(SchematicPreview.configuredKey(sha,Map.of("signed",locked)).equals(SchematicPreview.configuredKey(sha,overrides)),"Lock state does not invalidate geometry cache");check(!SchematicPreview.configuredKey(sha,overrides).equals(SchematicPreview.configuredKey(other,overrides)),"Configured cache includes source SHA");check(!SchematicPreview.configuredKey(sha,overrides).equals(SchematicPreview.configuredKey(sha,Map.of("signed",child.enabled(false)))),"Configured cache includes visibility");check(SchematicPreview.configuredKey(sha,Map.of()).equals(sha),"Unmodified source cache keys remain compatible");
        var configuredBytes=new ByteArrayOutputStream();SchematicPreview.writeOrbitModel(configuredModel,new DataOutputStream(configuredBytes),Cancellation.NEVER);var configuredRestored=SchematicPreview.readOrbitModel(new DataInputStream(new ByteArrayInputStream(configuredBytes.toByteArray())),Cancellation.NEVER);var restoredMirror=SchematicPreview.posedOrbitModel(configuredRestored,mirror,Cancellation.NEVER);check(Arrays.equals(SchematicPreview.renderOrbit(mirrored,.7,.4,false,Cancellation.NEVER),SchematicPreview.renderOrbit(restoredMirror,.7,.4,false,Cancellation.NEVER)),"Persisted configured model retains separate child transforms and source anchors");
        var fullField=configuredRestored.getClass().getDeclaredField("full");fullField.setAccessible(true);Object restoredGeometry=fullField.get(configuredRestored);var paletteField=restoredGeometry.getClass().getDeclaredField("palette");paletteField.setAccessible(true);var regionsField=restoredGeometry.getClass().getDeclaredField("regions");regionsField.setAccessible(true);Object sharedPalette=paletteField.get(restoredGeometry);for(Object part:(List<?>)regionsField.get(restoredGeometry)){var partGeometry=part.getClass().getDeclaredMethod("geometry");partGeometry.setAccessible(true);check(paletteField.get(partGeometry.invoke(part))==sharedPalette,"Configured regions share a single immutable palette allocation");}
        var configuredCache=new OrbitPreviewCache(temp.resolve("configured-cache"));String configuredKey=SchematicPreview.configuredKey(sha,overrides);configuredCache.write(configuredKey,configuredModel,Cancellation.NEVER);var reopened=new OrbitPreviewCache(temp.resolve("configured-cache")).read(configuredKey,Cancellation.NEVER);check(reopened!=null&&Arrays.equals(SchematicPreview.renderOrbit(reopened,.7,.4,false,Cancellation.NEVER),SchematicPreview.renderOrbit(configuredModel,.7,.4,false,Cancellation.NEVER)),"Fresh cache instance restores configured model");
        for(int turn=0;turn<4;turn++)for(boolean mx:new boolean[]{false,true})for(boolean mz:new boolean[]{false,true}){var pose=new PlacementTransform(Vec3i.ZERO,turn,mx,mz);var posed=SchematicPreview.posedOrbitModel(cubeModel,pose,Cancellation.NEVER);var shiftedPose=new PlacementTransform(new Vec3i(-400,500,123),turn,mx,mz);check(Arrays.equals(SchematicPreview.renderOrbit(posed,.8,.5,false,Cancellation.NEVER),SchematicPreview.renderOrbit(SchematicPreview.posedOrbitModel(cubeModel,shiftedPose,Cancellation.NEVER),.8,.5,false,Cancellation.NEVER)),"Root pose translation does not change pixels "+pose);}
        cancelled(()->SchematicPreview.readGeometry(placedSource,overrides,()->true));cancelled(()->SchematicPreview.posedOrbitModel(configuredModel,mirror,()->true));invalidOrbit(Arrays.copyOf(configuredBytes.toByteArray(),configuredBytes.size()-1));
        adaptive(temp);
        return checks;
    }
    private static int[] bounds(int[] pixels,int side){int x0=side,y0=side,x1=-1,y1=-1;for(int i=0;i<pixels.length;i++)if((pixels[i]>>>24)!=0){x0=Math.min(x0,i%side);y0=Math.min(y0,i/side);x1=Math.max(x1,i%side);y1=Math.max(y1,i/side);}return new int[]{x0,y0,x1,y1};}
    private static void adaptive(Path temp)throws Exception{
        var camera=PreviewCamera.DEFAULT.pan(30,-15,300);check(camera.panX()==.1&&camera.panY()==-.05&&camera.yaw()==PreviewCamera.DEFAULT.yaw(),"Middle drag changes only normalized camera pan");
        var zoomCamera=camera.scroll(3,.2,-.1);
        check(Math.abs((.2-camera.panX())/camera.zoom()-(.2-zoomCamera.panX())/zoomCamera.zoom())<1e-12&&Math.abs((-.1-camera.panY())/camera.zoom()-(-.1-zoomCamera.panY())/zoomCamera.zoom())<1e-12,"Wheel zoom retains the source point under the cursor anchor");
        var roundTrip=zoomCamera.scroll(-3,.2,-.1);check(Math.abs(roundTrip.zoom()-camera.zoom())<1e-12&&Math.abs(roundTrip.panX()-camera.panX())<1e-12&&Math.abs(roundTrip.panY()-camera.panY())<1e-12,"Unclipped zoom reverses without camera drift");
        check(camera.scroll(100,0,0).zoom()==16&&camera.scroll(-100,0,0).zoom()==.5,"Zoom extremes clamp to bounded model magnification");
        check(camera.pan(1e8,-1e8,100).panX()==16&&camera.pan(1e8,-1e8,100).panY()==-16,"Large middle drags stay bounded");
        check(camera.rotate(0,1e6,100).pitch()==PreviewCamera.MAX_PITCH&&camera.rotate(0,-1e6,100).pitch()==-PreviewCamera.MAX_PITCH,"Rotation cannot flip over the poles");
        for(Task invalid:List.<Task>of(()->camera.pan(1,1,0),()->camera.rotate(Double.NaN,0,300),()->camera.scroll(1,Double.POSITIVE_INFINITY,0),()->new PreviewCamera(0,0,Double.NaN,0,0))){try{invalid.run();throw new AssertionError("Nonfinite preview camera accepted");}catch(IllegalArgumentException expected){checks++;}}
        // Every coarse cell ends with green; only rereading the real packed source can recover red.
        int[] stripes=new int[320*16*8];for(int i=0;i<stripes.length;i++)stripes[i]=(i%320&1)==0?1:2;
        var source=root(Map.of("stripes",region(-160,-39,-4,320,16,8,stripes)));
        var sourceRegion=NbtReader.compound(NbtReader.compound(source.get("Regions"),"Regions").get("stripes"),"stripes");
        long[] words=((long[])sourceRegion.get("BlockStates")).clone();
        var baseGeometry=SchematicPreview.readGeometry(source,Cancellation.NEVER);
        var detailGeometry=SchematicPreview.readGeometry(source,Map.of(),SchematicPreview.DETAIL_LOD,Cancellation.NEVER);
        int[] colors={0xffff2020,0xff20ff20,0xff2020ff};
        var base=SchematicPreview.createOrbitModel(baseGeometry,colors,Cancellation.NEVER);
        var fine=SchematicPreview.createOrbitModel(detailGeometry,colors,Cancellation.NEVER);
        int[] coarsePixels=SchematicPreview.renderOrbit(base,base,0,0,2,0,0,256,false,Cancellation.NEVER);
        int[] finePixels=SchematicPreview.renderOrbit(fine,base,0,0,2,0,0,256,false,Cancellation.NEVER);
        check(center(coarsePixels,0)[2]==0&&center(finePixels,0)[2]>100,"Fine source reconstruction restores narrow red stripes lost by the 160-cell model");
        check(center(finePixels,1)[2]>100,"Recovered detail retains neighboring green stripes");
        png(temp.resolve("adaptive-base.png"),coarsePixels);png(temp.resolve("adaptive-detail.png"),finePixels);
        check(Arrays.equals(words,(long[])sourceRegion.get("BlockStates")),"Refinement and camera rendering never mutate packed source");
        for(double yaw:new double[]{0,.7,-1.1}){
            int[] low=SchematicPreview.renderOrbit(base,base,yaw,.23,.6,0,0,256,false,Cancellation.NEVER);
            int[] high=SchematicPreview.renderOrbit(fine,base,yaw,.23,.6,0,0,256,false,Cancellation.NEVER);
            check(Arrays.equals(bounds(low,256),bounds(high,256)),"Fine upgrade retains the base camera silhouette at yaw "+yaw);
        }
        var singleGeometry=SchematicPreview.readGeometry(root(Map.of("one",region(-5,-39,8,1,1,1,new int[]{1}))),Cancellation.NEVER);
        var single=SchematicPreview.createOrbitModel(singleGeometry,colors,Cancellation.NEVER);
        int[] centered=SchematicPreview.renderOrbit(single,single,.7,.4,.5,0,0,256,false,Cancellation.NEVER);
        int[] panned=SchematicPreview.renderOrbit(single,single,.7,.4,.5,.125,-.125,256,false,Cancellation.NEVER);
        int[] a=bounds(centered,256),b=bounds(panned,256);
        check(b[0]-a[0]==32&&b[2]-a[2]==32&&b[1]-a[1]==-32&&b[3]-a[3]==-32,"Pan is exactly normalized viewport displacement on both axes");
        check(count(centered)==count(panned),"Unclipped panning preserves coverage");
        int[] zoomed=SchematicPreview.renderOrbit(single,single,.7,.4,1,0,0,256,false,Cancellation.NEVER);
        check(count(zoomed)>count(centered)*3.8&&count(zoomed)<count(centered)*4.2,"Twofold camera zoom increases projected area fourfold");
        for(int side:new int[]{128,512,1024}){var pixels=SchematicPreview.renderOrbit(single,single,.7,.4,.5,0,0,side,false,Cancellation.NEVER);check(pixels.length==side*side&&count(pixels)>0,"Viewport resolution really changes raster size "+side);}
        for(double[] invalidCamera:new double[][]{{.49,0,0,256},{16.01,0,0,256},{1,16.01,0,256},{1,0,-16.01,256},{1,0,0,127},{1,0,0,1025},{Double.NaN,0,0,256}}){try{SchematicPreview.renderOrbit(single,single,0,0,invalidCamera[0],invalidCamera[1],invalidCamera[2],(int)invalidCamera[3],false,Cancellation.NEVER);throw new AssertionError("Invalid camera accepted");}catch(IllegalArgumentException expected){checks++;}}
        var insideTriangle=new java.util.concurrent.atomic.AtomicBoolean();
        cancelled(()->SchematicPreview.renderOrbit(single,single,0,0,16,0,0,1024,false,()->{
            boolean rasterizing=StackWalker.getInstance().walk(frames->frames.anyMatch(f->f.getMethodName().equals("triangle")&&f.getClassName().contains("SchematicPreview")));
            if(rasterizing)insideTriangle.set(true);return rasterizing;
        }));
        check(insideTriangle.get(),"Cancellation is checked inside a screen-covering triangle, not only between voxels");
        cancelled(()->SchematicPreview.readGeometry(source,Map.of(),SchematicPreview.DETAIL_LOD,()->true));
        var cachePath=temp.resolve("fine-cache");String key="d".repeat(64);new OrbitPreviewCache(cachePath,true).write(key,fine,Cancellation.NEVER);
        var restored=new OrbitPreviewCache(cachePath,true).read(key,Cancellation.NEVER);
        check(restored!=null&&Arrays.equals(finePixels,SchematicPreview.renderOrbit(restored,base,0,0,2,0,0,256,false,Cancellation.NEVER)),"Fresh detail cache restores fine geometry with unchanged base framing");
        check(new OrbitPreviewCache(cachePath).read(key,Cancellation.NEVER)==null,"Base cache reader cannot accept a fine grid exceeding its budget");
        var bytes=new ByteArrayOutputStream();SchematicPreview.writeOrbitModel(fine,new DataOutputStream(bytes),Cancellation.NEVER);
        byte[] corrupt=bytes.toByteArray();java.nio.ByteBuffer.wrap(corrupt).putInt(4,321);
        try{SchematicPreview.readOrbitModel(new DataInputStream(new ByteArrayInputStream(corrupt)),Cancellation.NEVER,true);throw new AssertionError("Oversize fine dimension accepted");}catch(IOException expected){checks++;}
    }
    public static void main(String[] args)throws Exception{Path temp=args.length==0?Files.createTempDirectory("preview-checks-"):Path.of(args[0]);System.out.println("SchematicPreviewChecks: "+run(temp)+" checks; fixtures "+temp);}
}
