package dev.betterlitematica.fabric;
import java.util.*;
import net.minecraft.client.MinecraftClient;
import net.minecraft.client.gui.DrawContext;
import dev.betterlitematica.core.UiViewport;
/** Compact read-only in-world overlay; inventories are grouped only in presentation snapshots. */
final class ProjectionInformation {
    private record Panel(ProjectionInfoData.Side side,List<String> lines,boolean more,int slots,int columns,int height){}
    private ProjectionInfoData.Snapshot data;private ProjectionController controller;private Panel projection,actual;private int updates;
    private Panel prepare(ProjectionInfoData.Side source){var side=ProjectionInventoryView.compact(source);var all=ProjectionInfoPanel.lines(side,controller.options().display.informationStates);int count=Math.min(8,all.size()),slots=Math.min(54,side.items().size()),columns=Math.max(1,Math.min(9,side.columns()));boolean more=count<all.size()||slots<side.items().size();int h=28+count*12+(slots==0?0:6+((slots+columns-1)/columns)*26)+(more?12:0);return new Panel(side,List.copyOf(all.subList(0,count)),more,slots,columns,h);}
    void update(MinecraftClient client,ProjectionController controller){this.controller=controller;if(client.player==null||!controller.options().display.information){data=null;return;}var target=controller.target(12);if(target==null){data=null;return;}if(data==null||!data.position().equals(target.position())||++updates%3==0){data=ProjectionInfoData.capture(client,controller,target);projection=prepare(data.projection());actual=prepare(data.actual());}}
    void render(MinecraftClient client,DrawContext ctx){if(data==null||client.currentScreen!=null||!controller.options().display.information)return;var w=client.getWindow();var view=UiViewport.fit(Math.max(1,w.getFramebufferWidth()),Math.max(1,w.getFramebufferHeight()),Math.max(1,w.getScaledWidth()),Math.max(1,w.getScaledHeight()),w.getScaleFactor());var ui=IndependentUi.INSTANCE;if(!ui.begin(ctx,view))return;try{boolean showActual=controller.options().display.informationWorld,stacked=!showActual||projection.height()+actual.height()+12<=336;int x=stacked?350:104;var p=data.position();ui.rect(x-6,12,598,32,UiTheme.PANEL);ui.text("X "+p.x()+"   Y "+p.y()+"   Z "+p.z(),x,16,590-x,UiTheme.TEXT);panel(ui,projection,"投影",x,36);if(showActual)panel(ui,actual,"实际",stacked?350:356,stacked?42+projection.height():36);}finally{ui.end();}}
    private void panel(IndependentUi ui,Panel panel,String title,int x,int y){int width=236;var side=panel.side();ui.rect(x-6,y-4,x+width+6,y+panel.height(),UiTheme.PANEL);if(side.state()!=null){ui.item(new net.minecraft.item.ItemStack(side.state().getBlock().asItem()),x,y,20);ui.text(title+" · "+side.state().getBlock().getName().getString(),x+26,y+3,width-26,UiTheme.TEXT);}else ui.text(title+" · 未加载",x,y+3,width,UiTheme.SECONDARY);double ly=y+26;for(String line:panel.lines()){ui.text(line,x,ly,width,UiTheme.SECONDARY);ly+=12;}ly+=4;for(int i=0;i<panel.slots();i++){double sx=x+(i%panel.columns())*26,sy=ly+(i/panel.columns())*26;ui.rect(sx,sy,sx+24,sy+24,UiTheme.INPUT);var item=side.items().get(i);if(!item.isEmpty()){ui.item(item,sx+2,sy+1,20);if(item.getCount()>1)ui.itemCount(item.getCount(),sx+1,sy+13,25);}}if(panel.more())ui.text("…",x,y+panel.height()-12,width,UiTheme.SECONDARY);}
}
