package dev.betterlitematica.fabric;
import java.util.*;

/** Every declared setting must have an explicit player-facing name and explanation. */
final class SettingHelp {
    record Definition(String label,String description){}
    private static final Map<SettingId,Definition> HELP=new EnumMap<>(SettingId.class);
    static {
        put(SettingId.PRINTER_PRINT,"打印","按投影放置缺失方块；按施工开关键开始或暂停。");
        put(SettingId.PRINTER_MINE,"挖掘","清理错误方块、多余方块或错误状态。");
        put(SettingId.PRINTER_FILL,"填充","用指定填充方块填充所选范围。");
        put(SettingId.PRINTER_DRAIN,"排流体","使用填充方块清理选定流体。");
        put(SettingId.PRINTER_BEDROCK,"破基岩","按破基岩范围移除基岩；选区模式无需加载投影，需生存模式、活塞、红石火把和足够的实际破坏速度。");
        put(SettingId.PRINTER_PRINT_SCOPE,"打印范围","选择按投影或选区限制打印与挖掘。");
        put(SettingId.PRINTER_FILL_SCOPE,"填充范围","选择填充作用的投影或选区范围。");
        put(SettingId.PRINTER_FLUID_SCOPE,"排流体范围","选择清理流体的投影或选区范围。");
        put(SettingId.PRINTER_BEDROCK_SCOPE,"破基岩范围","选区：破除选区内基岩；投影：仅破除与投影不符的基岩。始终遵守距离、分层和白名单。");
        put(SettingId.PRINTER_FILL_STATE,"填充方块","输入方块 ID 和状态，用于填充与排流体。");
        put(SettingId.PRINTER_FILL_DIRECTION,"方向","循环填充方块的可用方向。");
        put(SettingId.PRINTER_RANGE,"距离（0 自动）","限制施工距离；0 使用当前可交互距离。");
        put(SettingId.PRINTER_INTERVAL,"批次间隔 / tick","设置两批施工之间的等待 tick；0 或 1 每 tick 尝试。");
        put(SettingId.PRINTER_PER_TICK,"每 tick 上限","限制每 tick 的操作数量；0 按时间预算执行。");
        put(SettingId.PRINTER_COOLDOWN,"位置冷却 / tick","设置同一位置再次尝试前的等待时间。");
        put(SettingId.PRINTER_HUD,"状态 HUD","显示施工进度、受阻原因和必要的缺料物品。");
        put(SettingId.PRINTER_NEARBY_HUD,"周围待建 HUD","额外显示范围内所有待建方块；停止时也更新，不扣库存。");
        put(SettingId.PRINTER_SHAPE,"范围形状","选择球形、八面体或立方体施工范围。");
        put(SettingId.PRINTER_ORDER,"顺序","选择扫描位置的坐标轴顺序。");
        put(SettingId.PRINTER_REVERSE_X,"X 反向","反转 X 轴的施工扫描顺序。");
        put(SettingId.PRINTER_REVERSE_Y,"Y 反向","反转 Y 轴的施工扫描顺序。");
        put(SettingId.PRINTER_REVERSE_Z,"Z 反向","反转 Z 轴的施工扫描顺序。");
        put(SettingId.PRINTER_AIR_PLACE,"悬空放置","允许服务器支持时不依赖相邻支撑面放置。");
        put(SettingId.PRINTER_FALLING_CHECK,"重力方块支撑检查","放置沙子等重力方块前检查下方支撑。");
        put(SettingId.PRINTER_REPLACE,"替换可替换方块","允许替换名单中可被替换的草、雪等方块。");
        put(SettingId.PRINTER_STRIP_LOGS,"原木去皮","允许使用斧头把原木调整为投影要求的去皮状态。");
        put(SettingId.PRINTER_NOTE_TUNING,"音符盒调音","允许点击音符盒调整音高。");
        put(SettingId.PRINTER_BONEMEAL,"作物催熟","允许使用骨粉使作物达到投影要求的生长状态。");
        put(SettingId.PRINTER_COMPOSTER,"堆肥","允许向堆肥桶加入指定名单内的材料。");
        put(SettingId.PRINTER_BREAK_WRONG,"破坏错误方块","允许挖掉与投影类型不同的方块。");
        put(SettingId.PRINTER_BREAK_EXTRA,"破坏多余方块","允许挖掉投影要求为空气的位置。");
        put(SettingId.PRINTER_BREAK_STATE,"破坏错误状态","允许挖掉类型相同但状态不同的方块。");
        put(SettingId.PRINTER_FLOWING,"清理流水","排流体时同时处理流动水或流动岩浆。");
        put(SettingId.PRINTER_SKIP_WATERLOGGED,"跳过含水方块","跳过投影中要求含水状态的方块。");
        put(SettingId.PRINTER_FORCE_SNEAK,"潜行放置","放置时使用潜行，避免打开容器等交互。");
        put(SettingId.PRINTER_ICE_WATER,"破冰放水","允许放置并破坏冰以得到所需水源。");
        put(SettingId.PRINTER_CORAL,"珊瑚替代","允许放置活珊瑚并等待其变成目标失活珊瑚。");
        put(SettingId.PRINTER_SAFE_OBSERVER,"侦测器顺序检查","等侦测器前方的目标完成后再放置侦测器。");
        put(SettingId.PRINTER_CONTAINER_FILL,"容器填充","按投影内容向箱子等容器中补入物品。");
        put(SettingId.PRINTER_SUPPLY,"补给","选择潜影盒取料协议；自动模式检测服务器的 Quick Shulker 通道。");
        put(SettingId.PRINTER_SKIP,"跳过方块","设置打印时忽略的方块 ID 名单。");
        put(SettingId.PRINTER_REPLACEABLE,"可替换方块","设置允许替换的方块 ID 名单。");
        put(SettingId.PRINTER_FLUIDS,"清理流体","设置排流体处理的流体 ID 名单。");
        put(SettingId.PRINTER_COMPOST_ITEMS,"堆肥材料","设置可用于填充堆肥桶的物品 ID 名单。");
        put(SettingId.PRINTER_THREADS,"搜索线程","设置后台发现施工任务的线程数量。");
        put(SettingId.PRINTER_BREAK_INTERVAL,"破坏间隔 / tick","设置两批挖掘操作之间的等待时间。");
        put(SettingId.PRINTER_BREAK_PER_TICK,"每 tick 破坏上限","限制每 tick 的挖掘操作数；0 按时间预算执行。");
        put(SettingId.PRINTER_BUDGET,"工作预算 / ms","限制每 tick 搜索与施工消耗的时间。");
        put(SettingId.PRINTER_HIGHLIGHTS,"施工高亮","显示最近放置、调节、破坏和失败的位置。");
        put(SettingId.PRINTER_HIGHLIGHT_ON_TOP,"高亮置顶","让施工高亮穿过方块保持可见。");
        put(SettingId.PRINTER_HIGHLIGHT_STYLE,"样式","选择高亮轮廓、填充或两者同时显示。");
        put(SettingId.PRINTER_HIGHLIGHT_TIME,"时长 / ms","设置高亮持续时间；放置反馈最长 450 ms。");
        put(SettingId.PRINTER_HIGHLIGHT_RANGE,"高亮范围 / 格","限制显示施工高亮的距离。");
        put(SettingId.PRINTER_HIGHLIGHT_LIMIT,"高亮上限","限制同时显示的高亮数量；0 不限。");
        put(SettingId.PRINTER_PLACE_COLOR,"放置颜色","设置放置反馈的 ARGB 颜色；点击色块选色。");
        put(SettingId.PRINTER_ADJUST_COLOR,"调节颜色","设置调节反馈的 ARGB 颜色；点击色块选色。");
        put(SettingId.PRINTER_BREAK_COLOR,"破坏颜色","设置破坏反馈的 ARGB 颜色；点击色块选色。");
        put(SettingId.PRINTER_FAILED_COLOR,"失败颜色","设置失败反馈的 ARGB 颜色；点击色块选色。");
        put(SettingId.PRINTER_RESET_COLORS,"恢复默认","恢复当前页的默认颜色。");
        put(SettingId.BEDROCK_EMPTY_HAND,"空手右键切换","空手右键目标时将其加入或移出独立破基岩队列。");
        put(SettingId.BEDROCK_SHORT_WAIT,"瞬挖短等待","缩短支持瞬间挖掘时的动作等待。");
        put(SettingId.BEDROCK_TIMEOUT,"任务超时 / tick","超过等待时间后停止当前目标并按重试次数处理。");
        put(SettingId.BEDROCK_RETRIES,"重试次数","设置破除失败后重新尝试当前目标的次数。");
        put(SettingId.BEDROCK_HELD_TOOL,"手持工具兼容","使用启动时手持的物品（也可空手）尝试，不受客户端速度预测限制；适用于其他模组或高等级效果造成的速度预测差异，最终以服务器确认为准。关闭时按实际速度自动选取，不限工具类型、附魔和效果等级。");
        put(SettingId.BEDROCK_DEBUG,"调试日志","记录破基岩步骤，便于排查失败原因。");
        put(SettingId.BEDROCK_WHITELIST,"允许方块","设置独立破基岩任务接受的方块名单。");
        put(SettingId.BEDROCK_EXCLUDED_Y,"排除 Y 层","禁止在指定高度创建破基岩任务。");
        put(SettingId.OPTIONS_TOOL,"选区工具","启用选区工具的点击与编辑操作。");
        put(SettingId.OPTIONS_TOOL_SETTINGS,"工具设置","打开工具物品和选区操作设置。");
        put(SettingId.OPTIONS_EASY_PLACE,"简单放置","用投影选择材料与放置状态。");
        put(SettingId.OPTIONS_HOLD,"按住连续","简单放置开启时，按住左键或右键扫过投影连续放置；新位置立即尝试，同一位置短暂等待确认。");
        put(SettingId.OPTIONS_RESTRICTION,"放置限制","阻止在不符合投影的位置放置。");
        put(SettingId.OPTIONS_PICK,"投影拾取","允许拾取投影对应的物品。");
        put(SettingId.OPTIONS_ACCURATE,"精确放置","选择服务器支持的精确放置协议。");
        put(SettingId.OPTIONS_INVENTORY,"取料与工具","设置受保护的背包栏位与工具物品。");
        put(SettingId.OPTIONS_COMPATIBILITY,"模组共存","查看检测到的模组与功能接管说明。");
        put(SettingId.DISPLAY_THEME,"界面主题","切换瓷白或曜石界面配色。");
        put(SettingId.DISPLAY_ERROR_STYLE,"错误样式","选择世界差异的轮廓或填充显示方式。");
        put(SettingId.DISPLAY_BUILD_BUDGET,"加载预算","每帧用于生成投影的最长时间；越高加载越快，加载期间帧率可能下降，加载完成后不占用。");
        put(SettingId.DISPLAY_PROJECTION,"投影方块","显示或隐藏投影的方块模型。");
        put(SettingId.DISPLAY_LAYERS,"分层","选择投影显示与施工的层范围。");
        put(SettingId.DISPLAY_PLACEMENT_BOUNDS,"摆放边框","显示各投影摆放的外边界。");
        put(SettingId.DISPLAY_REGION_BOUNDS,"子区域边框","显示投影内部子区域的边界。");
        put(SettingId.DISPLAY_SELECTION_BOUNDS,"选区边框","显示当前编辑选区的边界。");
        put(SettingId.DISPLAY_ORIGINS,"原点","显示摆放与选区的原点标记。");
        put(SettingId.DISPLAY_INFORMATION,"方块信息","显示准星指向方块的投影信息。");
        put(SettingId.DISPLAY_WORLD_INFORMATION,"实际方块信息","同时显示世界中实际方块的信息。");
        put(SettingId.DISPLAY_STATES,"方块状态","在方块信息中显示方向、含水等状态。");
        put(SettingId.BEDROCK_BREAK_DOWN,"破坏向下","切换向下破坏目标；至少保留一个破坏方向。");
        put(SettingId.BEDROCK_BREAK_UP,"破坏向上","切换向上破坏目标；至少保留一个破坏方向。");
        put(SettingId.BEDROCK_BREAK_NORTH,"破坏向北","切换向北破坏目标；至少保留一个破坏方向。");
        put(SettingId.BEDROCK_BREAK_SOUTH,"破坏向南","切换向南破坏目标；至少保留一个破坏方向。");
        put(SettingId.BEDROCK_BREAK_WEST,"破坏向西","切换向西破坏目标；至少保留一个破坏方向。");
        put(SettingId.BEDROCK_BREAK_EAST,"破坏向东","切换向东破坏目标；至少保留一个破坏方向。");
        put(SettingId.BEDROCK_PISTON_DOWN,"活塞朝下","切换初始活塞朝下；至少保留一个朝向。");
        put(SettingId.BEDROCK_PISTON_UP,"活塞朝上","切换初始活塞朝上；至少保留一个朝向。");
        for(var id:SettingId.values())require(id);
    }
    private static void put(SettingId id,String label,String description){if(HELP.put(id,new Definition(label,description))!=null)throw new IllegalStateException("设置说明重复："+id);}
    static Definition require(SettingId id){var value=HELP.get(Objects.requireNonNull(id));if(value==null||value.label().isBlank()||value.description().isBlank())throw new IllegalStateException("设置缺少说明："+id);return value;}
    static String text(SettingId id){return require(id).description();}
}
